name: React CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js
    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build Project
    - name: Build Project
      run: npm run build

    # Step 5: Deploy to Server
    - name: Deploy to Server
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}         # SFTP Host (Add as a repository secret)
        SFTP_USER: ${{ secrets.SFTP_USER }}         # SFTP Username (Add as a repository secret)
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }} # SFTP Password (Add as a repository secret)
      run: |
        # Enable debugging to capture detailed logs
        set -x

        # Log the SFTP details (excluding password)
        echo "SFTP Host: $SFTP_HOST"
        echo "SFTP User: $SFTP_USER"
        
        # Check if lftp is installed, install if necessary
        if ! command -v lftp &> /dev/null
        then
          echo "lftp not found. Installing..."
          sudo apt-get update && sudo apt-get install -y lftp
        else
          echo "lftp is already installed."
        fi

        # Use lftp to deploy the build folder with bypass for host key verification
        echo "Starting deployment..."
        lftp -c "
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null';
          open -u $SFTP_USER,$SFTP_PASSWORD sftp://$SFTP_HOST;
          mirror -R ./build /home/$SFTP_USER/public_html/react/;
        "

        # Disable debugging
        set +x
        echo "Deployment completed successfully."
